CS2340Proj2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_home(_request):
    """
    Redirect to the home page
    """
    return redirect("/home")

urlpatterns = [
    path("", redirect_to_home),
    path("home/", include("home.urls")),
    path("wrapped/", include("wrapped.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path("", views.index, name="home"),
    path("profile/", views.profile, name="profile"),
    path("profile/delete", views.delete, name="delete_user"),
    path("create-wrap/", views.create_wrap_view, name="create_wrap"),
    path('wrapped/<int:wrapped_id>/', views.wrapped_detail_view, name='wrapped_detail'),
    path('api/wraps/<int:wrap_id>/', views.delete_wrap, name='delete_wrap'),
]

wrapped/urls.py
from django.urls import path

from wrapped import views

urlpatterns = [
    path("", views.wrapped, name="wrapped"),
]

home/models.py
"""
Models for Spotify Wrapped
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Artist(models.Model):
    """
    Model for artist to be used in wrapped
    name: name of the artist
    icon_href: href to the icon of the artist
    """
    name = models.CharField(max_length=128, default="")
    icon_href = models.CharField(max_length=128, default="")

class Song(models.Model):
    """
    Model for song to be used in wrapped
    name: name of the song
    artist: foreign key to the artist of the song
    album: name of the album the song is in
    genre: genre of the song
    icon_href: href to the icon of the song
    """
    name = models.CharField(max_length=128, default="")
    artist_name = models.CharField(max_length=128, default="")
    album = models.CharField(max_length=128, default="")
    icon_href = models.CharField(max_length=128, default="")


class Wrapped(models.Model):
    """
    Data for spotify wrapped
    user: foreign key to the user that the wrapped is for
    date: date of the wrapped
    top_songs: many to many relationship to the top songs of the wrapped, 
    relation includes a rank

    top_artists: many to many relationship to the top artists of the wrapped, 
    relation includes a rank

    reccomended_songs: many to many relationship to the reccomended songs of the wrapped
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    top_songs = models.ManyToManyField(Song, through='TopSongRel',
                                       related_name='top_songs')
    top_weekly_songs = models.ManyToManyField(Song, through='TopWeeklySongRel',
                                              related_name='top_weekly_songs')
    top_artists = models.ManyToManyField(Artist, through='TopArtistRel',
                                         related_name='top_artists')
    top_weekly_artists = models.ManyToManyField(Artist, through='TopWeeklyArtistRel',
                                                related_name='top_weekly_artists')
    recomended_songs = models.ManyToManyField(Song, related_name='recomended_songs')


class TopSongRel(models.Model):
    """
    Model for top song relation
    wrapped: foreign key to the wrapped that the song is in
    song: foreign key to the song
    rank: rank of the song in the wrapped
    """
    wrapped = models.ForeignKey(Wrapped, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    rank = models.IntegerField(default=-1)

class TopWeeklySongRel(models.Model):
    """
    Model for top weekly song relation
    wrapped: foreign key to the wrapped that the song is in
    song: foreign key to the song
    rank: rank of the song in the wrapped
    """
    wrapped = models.ForeignKey(Wrapped, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    rank = models.IntegerField(default=-1)

class TopArtistRel(models.Model):
    """
    Model for top artist relation
    wrapped: foreign key to the wrapped that the artist is in
    song: foreign key to the artist
    rank: rank of the artist in the wrapped
    """
    wrapped = models.ForeignKey(Wrapped, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    rank = models.IntegerField(default=-1)

class TopWeeklyArtistRel(models.Model):
    """
    Model for top weekly artist relation
    wrapped: foreign key to the wrapped that the artist is in
    song: foreign key to the artist
    rank: rank of the artist in the wrapped
    """
    wrapped = models.ForeignKey(Wrapped, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    rank = models.IntegerField(default=-1)

wrapped/models.py
# Create your models here.

home/views.py
"""
Views for the Spotify Wrapped app.
"""

from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.utils.timezone import now
from django.http import JsonResponse, HttpResponseForbidden
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from accounts.models import SpotifyToken
from accounts.views import refresh_spotify_token
from home.spotify_api import SpotifyAPI, create_wrapped
from home.models import Wrapped
# Create your views here.

def check_authenticated(request):
    """
    Check if the user is authenticated
    """
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    return None


def redirect_to_account(request):
    """
    Redirect to the account page
    """
    redirect_response = check_authenticated(request)
    if redirect_response:
        return redirect_response
    wraps = Wrapped.objects.filter(user=request.user).order_by('-date')
    refresh_spotify_token(request.user)
    return render(request, "home/home.html", {'wraps': wraps})

def index(request):
    """
    Index view
    """
    redirect_response = check_authenticated(request)
    if redirect_response:
        return redirect_response
    wraps = Wrapped.objects.filter(user=request.user).order_by('-date')
    refresh_spotify_token(request.user)
    return render(request, "home/home.html", {'wraps': wraps})

def profile(request):
    """
    Profile view
    """
    redirect_response = check_authenticated(request)
    if redirect_response:
        return redirect_response

    return render(request, "home/profile.html", {"username": request.user.username})


def delete(request):
    """
    Delete user view
    """
    redirect_response = check_authenticated(request)
    if redirect_response:
        return redirect_response

    try:
        user = request.user
        user.delete()
    except Exception as _e:
        pass
    return redirect("login")

def create_wrap_view(request):
    """
    Create a wrapped view
    """
    try:
        # Retrieve the user's Spotify token
        spotify_token = SpotifyToken.objects.get(user=request.user)

        # Check token expiration
        if spotify_token.expires_in <= now():
            # Handle token refresh logic (not implemented in this snippet)
            return redirect("refresh_spotify_token")

        # Instantiate the Spotify API with the user's access token
        spotify_api = SpotifyAPI(spotify_token.access_token)

        # Create the Wrapped object
        wrapped = create_wrapped(request.user, spotify_api)
        # Generate the URL for the wrapped detail page
        wrapped_url = reverse('wrapped_detail', kwargs={'wrapped_id': wrapped.id})

        # Redirect to the wrapped detail page with the wrapped id in the URL
        return JsonResponse({'wrapped_url': wrapped_url})

    except SpotifyToken.DoesNotExist:
        return render(request, "error.html", {"message": "Spotify token not found."})

def wrapped_detail_view(request, wrapped_id):
    """
    View wrapped detail view
    """
    # Retrieve the wrapped object using the wrapped_id
    wrapped = get_object_or_404(Wrapped, id=wrapped_id)
    top_songs = wrapped.top_songs.through.objects.filter(wrapped=wrapped).order_by('rank')
    top_weekly_songs = wrapped.top_weekly_songs.through.objects.filter(
        wrapped=wrapped
        ).order_by('rank')
    top_artists = wrapped.top_artists.through.objects.filter(
        wrapped=wrapped
        ).order_by('rank')
    top_weekly_artists = wrapped.top_weekly_artists.through.objects.filter(
        wrapped=wrapped
        ).order_by('rank')

    context = {
        'wrapped': wrapped,
        'top_songs': top_songs,
        'top_weekly_songs': top_weekly_songs,
        'top_artists': top_artists,
        'top_weekly_artists': top_weekly_artists,
        'recommended_songs': wrapped.recomended_songs.all(),
    }
    return render(request, 'home/wrapped.html', context)

@login_required
def delete_wrap(request, wrap_id):
    """
    Delete wrap view
    """
    if request.method == 'DELETE':
        wrap = get_object_or_404(Wrapped, id=wrap_id, user=request.user)
        wrap.delete()
        return JsonResponse({'message': 'Wrap deleted successfully!'}, status=200)
    return HttpResponseForbidden("You are not allowed to perform this action.")

wrapped/views.py
"""
View for the wrapped page
"""

from django.shortcuts import render, redirect
from django.conf import settings

def wrapped(request):
    """
    Get view for the wrapped page
    """
    if not request.user.is_authenticated:
        # Redirect to the login page if the user is not logged in
        return redirect(settings.LOGIN_URL)

    # Render the home page if the user is logged in
    return render(request, "wrapped/wrapped.html", {})

home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

</head>
<body>

<div class="container">
    <!-- Header with Spotify Logo and Logout Icon -->
    <header class="header">
        <img src="{% static 'images/spotify_icon.png' %}" alt="Spotify Wrapped Icon" class="logo">
        <div class="profile-section">
            <a href="{% url 'profile' %}" style="">
                <button class="profile-icon">Profile</button>
            </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="logout-icon"><i class="fas fa-sign-out-alt"></i>
                </button>
            </form>
        </div>

    </header>

    <!-- Create Wrap Button -->
    <div class="create-wrap-section">
        <button class="create-wrap-button">
            <i class="fas fa-play play-icon"></i>
            <b>Create Wrap</b>
        </button>
    </div>

    <script>
        document.querySelector(".create-wrap-button").addEventListener("click", () => {
            fetch("{% url 'create_wrap' %}", {
                method: "POST",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}"
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.wrapped_url) {
                    // Open the wrapped URL in a new tab
                    window.open(data.wrapped_url, '_blank');
                    window.location.reload();

                } else {
                    alert("Error creating Wrapped!");
                }
            })
            .catch(error => {
                alert(error);
            });
        });
        </script>

    <!-- Scrollable Previous Wraps Section -->
    <div class="previous-wraps-section">
    <h2>Previous Wraps...</h2>
    <div class="wraps-container">
        {% for wrapped in wraps %}
        <div class="wrap-item">
            <a href="/home/wrapped/{{ wrapped.id }}" class="wrap-link">
                <p>{{ wrapped.date }}</p>
            </a>
            <button class="delete-wrap" data-id="{{ wrapped.id }}" aria-label="Delete Wrap">
                🗑️
            </button>
        </div>
        {% endfor %}
    </div>
</div>

    

</div>
<script>
    // Handle the delete button click
    document.addEventListener('click', async (event) => {
        if (event.target.classList.contains('delete-wrap')) {
            const wrapId = event.target.dataset.id;

            // Send DELETE request
            const response = await fetch(`api/wraps/${wrapId}/`, {
                method: 'DELETE',
                headers: {
                    'X-CSRFToken': getCookie('csrftoken'), // Include CSRF token
                },
            });

            if (response.ok) {
                // Remove the wrap item from the DOM
                window.location.reload();
            } else {
                console.error('Failed to delete wrap:', response.statusText);
            }


        }
    });

    // Helper function to get the CSRF token
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === name + '=') {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
</body>
</html>

home/templates/home/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body>

<div class="container">
    <!-- Header with Spotify Logo and Logout Icon -->
    <header class="header">
        <img src="{% static 'images/spotify_icon.png' %}" alt="Spotify Wrapped Icon" class="logo">
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="logout-icon"><i class="fas fa-sign-out-alt"></i>
            </button>
<!--            <a href="{% url 'logout' %}" class="logout-icon">-->
<!--            </a>-->
        </form>
    </header>

    <!-- Create Wrap Button -->
    <div class="create-wrap-section">
        <h2>Profile Details:</h2>
        <h3>Name: {{ username }}</h3>
        <form action="{% url 'delete_user' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="logout-icon"><i class="fas fa-sign-out-alt"></i>
                Delete Account
            </button>
        </form>
    </div>

</div>

</body>
</html>

home/templates/home/wrapped.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrollable Slides</title>
    <link rel="stylesheet" href="{% static 'css/wrapped.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>
    <a href="/home/" class="close-button" aria-label="Go back to home">×</a>
    <div class="slider-container">
        <div class="slider-wrapper">
            <div class="slide" style="">
                <h2>Here is your weekly Spotify Wrapped for {{ wrapped.date }}</h2>
            </div>
            <div class="slide" style="">
                <h2>Top Artists (Lifetime)</h2>
                <ul>
                    {% for artist_rel in wrapped.topartistrel_set.all|dictsort:"rank" %}
                    {% if artist_rel.rank > 1 %}
                    <li>
                        {{ artist_rel.rank }}: <span class="artist-name">{{ artist_rel.artist.name }}</span>
                        <img src="{{ artist_rel.artist.icon_href }}" alt="Artist Icon" height="50px" width="50px">
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="slide" style="">
                {% with wrapped.topartistrel_set.all|dictsort:"rank" as sorted_artists %}
                {% if sorted_artists|length > 0 %}
                <h2>Top Artist (Lifetime)</h2>
                {% with sorted_artists|first as top_artist %}
                <div class="top-item">
                    <img src="{{ top_artist.artist.icon_href }}" alt="Artist Icon" height="100px" width="100px">
                    <p>1: {{ top_artist.artist.name }}</p>
                </div>
                {% endwith %}
                {% endif %}
                {% endwith %}
            </div>
            <div class="slide" style="">
                <h2>Top Artists (Weekly)</h2>
                <ul>
                    {% for artist_rel in wrapped.topweeklyartistrel_set.all|dictsort:"rank" %}
                    <li>
                        {{ artist_rel.rank }}: <span class="artist-name">{{ artist_rel.artist.name }}</span>
                        <img src="{{ artist_rel.artist.icon_href }}" alt="Artist Icon" height="50px" width="50px">
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="slide" style="">
                <h2>Top Songs (Lifetime)</h2>
                <ul>
                    {% for song_rel in wrapped.topsongrel_set.all|dictsort:"rank" %}
                    <li class="song-item">
                        <img src="{{ song_rel.song.icon_href }}" alt="Song Icon" class="song-icon">
                        <div class="song-details">
                            <span class="song-title">{{ song_rel.song.name }}</span>
                            <span class="artist-name-small">{{ song_rel.song.artist_name }}</span>
                        </div>
                        <span class="rank">#{{ song_rel.rank }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="slide" style="">
                {% with wrapped.topweeklysongrel_set.all|dictsort:"rank" as sorted_weekly_songs %}
                {% if sorted_weekly_songs|length > 0 %}
                <h2>Top Song (Weekly)</h2>
                {% with sorted_weekly_songs|first as top_weekly_song %}
                <div class="top-item">
                    <img src="{{ top_weekly_song.song.icon_href }}" alt="Song Icon" height="100px" width="100px">
                    <p>"{{ top_weekly_song.song.name }}"</p> by <p class="artist-name">{{ top_weekly_song.song.artist_name }}</p>
                </div>
                {% endwith %}
                {% endif %}
                {% endwith %}
            </div>
            <div class="slide" style="">
                <h2>Recommended Songs</h2>
                <ul>
                    {% for song in wrapped.recomended_songs.all %}
                    <li class="song-item">
                        <img src="{{ song.icon_href }}" alt="Song Icon" class="song-icon">
                        <div class="song-details">
                            <span class="song-title">{{ song.name }}</span>
                            <span class="artist-name-small">{{ song.artist_name }}</span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="slide" style="">
                <h2>Have a great day!</h2>
            </div>
        </div>

        <!-- Arrow buttons for desktop -->
        <button class="arrow left-arrow">&#8592;</button>
        <button class="arrow right-arrow">&#8594;</button>
    </div>

    <script src="{% static 'wrapped/wrapped.js' %}"></script>
</body>
</html>